### ISSUE TITLE
Link quebrado na aula

### ISSUE THREAD

**Issue by Schinemann** [vsvasconcelos/i2a2#1]
Boa noite!
Aula: m1_estatistica.ipynb
O link para o vídeo dos gráficos está quebrado no item  "Mais sobre visualizações..." .
Creio que o caminho seja este:
https://www.youtube.com/watch?v=0R-UQLRk4VI&list=PLxI8Can9yAHeeWqe3m9HZFiBhT33Mfxew&index=10

Att,

**Comment by vsvasconcelos** [comment]
Obrigado,

Vou verificar.

Em ter., 29 de mar. de 2022 21:24, Schinemann ***@***.***>
escreveu:
